(() => {
const q=s=>document.querySelector(s), make=(t,text,cls)=>{const x=document.createElement(t);if(text)x.textContent=text;if(cls)x.className=cls;return x;};
const clean=s=>String(s||'');
let token='',imageModels=[],running=false,refreshing=false,refreshPending=false;
function savedImageModel(){try{return localStorage.getItem('borgnet-image-model')||'';}catch{return '';}}
function rememberImageModel(){try{localStorage.setItem('borgnet-image-model',q('#localImageModel').value);}catch{}}
async function request(path,body){if(body!==undefined||!token)token=(await(await fetch('/api/state')).json()).token;const r=await fetch('/api/images/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-BorgNet-Token':token},body:JSON.stringify(body)});if(!r.ok){let e;try{e=await r.json();}catch{}throw Error(clean(e?.error||`Local service returned ${r.status}`));}return r;}
function panel(id,title,subtitle,content){const p=make('section',null,'panel local-mode-panel');p.id=id+'Panel';const h=make('div',null,'panel-heading');const text=make('div');text.append(make('p','IMAGE WORKSPACE','eyebrow'),make('h1',title),make('p',subtitle));h.append(text);p.append(h);p.insertAdjacentHTML('beforeend',content);q('#historyPanel').parentElement.append(p);const b=make('button',title);b.dataset.tab=id;b.addEventListener('click',()=>tab(id));q('.tabs').append(b);return p;}
panel('imagegen','Image generation','Your existing connections for images and chat.',`<form id="localImageForm" class="local-form"><div class="local-controls"><label>Image model<select id="localImageModel"></select></label><label>Generation mode<select id="localImageMode"><option value="draft">Draft · fewer steps</option><option value="balanced" selected>Balanced · model default</option><option value="detail">Detail · more steps</option></select></label><label>Size<select id="localImageSize"></select></label></div><p id="localImageInfo" class="caption"></p><label>Image prompt<textarea id="localImagePrompt" rows="4" maxlength="4000" required placeholder="Describe the image you want to create"></textarea></label><details><summary>Generation settings</summary><label>Negative prompt<textarea id="localImageNegative" rows="2" maxlength="2000"></textarea></label><div class="local-controls"><label>Steps<input id="localImageSteps" type="number" required></label><label>Seed (-1 for random)<input id="localImageSeed" type="number" value="-1" min="-1" max="2147483647"></label></div></details><button id="localImageGenerate" class="primary" disabled>Generate image ↑</button><button id="localImageConnect" type="button" class="subtle">Connect image API</button><button id="localImageRefresh" type="button" class="subtle">Refresh models</button><p id="localImageState" class="caption local-state" role="status"></p></form><div id="localImageOutput"></div><h2>Recent images</h2><p id="localImageActionStatus" class="caption local-state" role="status"></p><div id="localImageGallery" class="local-gallery"></div><details><summary>Recently deleted</summary><p class="caption">Deleted images stay here until restored.</p><div id="localImageTrash" class="local-gallery"></div></details>`);
const imageDialog=make('dialog');imageDialog.innerHTML=`<form id="imageApiForm"><div class="dialog-heading"><h2>Connect image API</h2><button id="imageApiClose" type="button" class="icon">×</button></div><label>Provider<select name="provider"><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option><option value="xai">xAI / Grok</option></select></label><label>API key<input name="api_key" type="password" required autocomplete="new-password"></label><p class="caption">Stored locally, separately from your configuration. Optional direct API connection. Existing configured provider credentials are reused when available.</p><p id="imageApiStatus" role="status"></p><button class="primary">Save and discover models</button></form>`;document.body.append(imageDialog);
q('#localImageConnect').addEventListener('click',()=>{q('#imageApiForm').reset();imageDialog.showModal();});q('#imageApiClose').addEventListener('click',()=>imageDialog.close());
q('#imageApiForm').addEventListener('submit',async e=>{e.preventDefault();try{if(!token)token=(await(await fetch('/api/state')).json()).token;const r=await fetch('/api/image-providers',{method:'POST',headers:{'Content-Type':'application/json','X-BorgNet-Token':token},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(!r.ok)throw Error('Could not save image API key');e.target.reset();imageDialog.close();window.dispatchEvent(new Event('borgnet-image-credentials-changed'));await refreshImages();}catch(e){q('#imageApiStatus').textContent=e.message;}});
function selectedImage(){return imageModels.find(x=>x.id===q('#localImageModel').value);}
function imageSettings(){const m=selectedImage();if(!m){q('#localImageGenerate').disabled=true;q('#localImageInfo').textContent='No image model available.';return;}q('#localImageMode').replaceChildren(...(m.modes||[['draft','Draft · fewer steps'],['balanced','Balanced · model default'],['detail','Detail · more steps']]).map(x=>new Option(x[1],x[0])));q('#localImageMode').value=m.modes?'auto':'balanced';q('#localImageSteps').disabled=Boolean(m.modes);q('#localImageSeed').disabled=Boolean(m.modes);q('#localImageSize').replaceChildren(...m.sizes.map(x=>new Option(x,x)));q('#localImageSize').value=m.default_size;q('#localImageSteps').min=m.min_steps;q('#localImageSteps').max=m.max_steps;steps();q('#localImageInfo').textContent=`${m.label} · ${m.backend==='signedin'?'Existing sign-in':m.backend==='api'?'Cloud image API':m.backend==='local_cli'?'Local Metal runtime':'Remote image runtime'} · ${clean(m.status)} · Text to image`;q('#localImageGenerate').disabled=running||!m.installed;}
function steps(){const m=selectedImage();if(m)q('#localImageSteps').value=q('#localImageMode').value==='draft'?m.min_steps:q('#localImageMode').value==='detail'?m.max_steps:m.default_steps;}
async function refreshImages(){if(running||refreshing){refreshPending=true;return;}refreshing=true;refreshPending=false;q('#localImageState').textContent='Discovering installed image models…';try{const d=await(await request('imagegen/models')).json(),previous=q('#localImageModel').value||savedImageModel();imageModels=d.models||[];q('#localImageModel').replaceChildren(...imageModels.map(m=>new Option(m.label+(m.installed?'':' · API key required'),m.id)));if(imageModels.some(m=>m.id===previous))q('#localImageModel').value=previous;else if(imageModels.some(m=>m.installed))q('#localImageModel').value=imageModels.find(m=>m.installed).id;rememberImageModel();imageSettings();q('#localImageState').textContent=`${imageModels.filter(m=>!['api','signedin'].includes(m.backend)&&m.installed).length} local model(s) · ${imageModels.filter(m=>m.backend==='api'&&m.installed).length} API model(s) with credentials · ${imageModels.filter(m=>m.backend==='signedin').length} signed-in image connection(s). Cloud generation uses your provider account.`;await gallery();}catch(e){q('#localImageState').textContent=e.message;q('#localImageGenerate').disabled=true;}finally{refreshing=false;if(refreshPending&&!running)refreshImages();}}
function imageURL(x){return /^\/api\/imagegen\/images\/\d{8}-\d{6}-[a-f0-9]{8}$/.test(x)?window.borgnetMediaURL(x.replace('/api/','/api/images/')):'';}
function imageActions(x,trashed=false){const row=make('div',null,'local-image-actions');for(const [action,label] of (trashed?[['restore','Restore']]:[['save','Save to Downloads'],['delete','Delete']])){const b=make('button',label,'subtle');b.type='button';b.addEventListener('click',async()=>{b.disabled=true;const status=q('#localImageActionStatus');try{const d=await(await request('imagegen/library',{id:x.id,action})).json();status.textContent=d.message;if(action==='delete'&&q('#localImageOutput').dataset.imageId===x.id)q('#localImageOutput').replaceChildren();await gallery();}catch(e){status.textContent=e.message;}finally{b.disabled=false;}});row.append(b);}return row;}
function showImage(x){const out=q('#localImageOutput'),url=imageURL(x.url);out.replaceChildren();out.dataset.imageId=x.id;if(!url)return;out.append(make('p',x.prompt,'local-message'));const img=make('img',null,'local-image');img.src=url;img.alt=x.prompt||'Generated image';out.append(img,imageActions(x));}
async function gallery(){const d=await(await request('imagegen/history')).json();for(const [key,selector,trashed] of [['images','#localImageGallery',false],['trash','#localImageTrash',true]]){const list=q(selector);list.replaceChildren();for(const x of (d[key]||[])){const url=imageURL(x.url);if(!url)continue;const card=make('div',null,'local-image-card'),b=make('button'),img=make('img');img.src=url;img.alt=x.prompt||'Generated image';b.type='button';b.append(img);if(!trashed)b.addEventListener('click',()=>showImage(x));else b.disabled=true;card.append(b,imageActions(x,trashed));list.append(card);}if(trashed&&!list.children.length)list.append(make('p','No deleted images.','caption'));}}
q('#localImageModel').addEventListener('change',()=>{rememberImageModel();imageSettings();});q('#localImageMode').addEventListener('change',steps);q('#localImageRefresh').addEventListener('click',refreshImages);
q('#localImageForm').addEventListener('submit',async e=>{e.preventDefault();if(running||!selectedImage()?.installed)return;running=true;q('#localImageGenerate').disabled=true;q('#localImageState').dataset.error='false';q('#localImageOutput').replaceChildren();q('#localImageState').textContent='Loading image runtime and generating…';try{const x=await(await request('imagegen/generate',{model_id:selectedImage().id,prompt:q('#localImagePrompt').value,negative_prompt:q('#localImageNegative').value,size:q('#localImageSize').value,steps:Number(q('#localImageSteps').value),seed:Number(q('#localImageSeed').value),quality:q('#localImageMode').value})).json();showImage(x);q('#localImageState').textContent='Image saved. '+clean(x.restoration_error?('Text runtime restoration needs attention: '+x.restoration_error):'');await gallery();}catch(e){q('#localImageState').dataset.error='true';q('#localImageState').textContent=e.message;}finally{running=false;imageSettings();if(refreshPending)refreshImages();}});
window.addEventListener('borgnet-tab-change',event=>{if(event.detail==='imagegen')refreshImages();});
window.addEventListener('borgnet-connections-changed',()=>refreshImages());
for(const id of ['localImagePrompt'])q('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.target.form.requestSubmit();}});
})();
