(() => {
const q=s=>document.querySelector(s), make=(t,text,cls)=>{const x=document.createElement(t);if(text)x.textContent=text;if(cls)x.className=cls;return x;};
const clean=s=>String(s||'');
let token='',imageModels=[],running=false,refreshing=false,refreshPending=false;
function imageSource(model){if(model?.id?.startsWith('local::')||model?.backend==='local_cli')return 'local';if(/^api::(openrouter|horde|pollinations)::/.test(model?.id||''))return 'community';return 'frontier';}
let sourceGroup;try{sourceGroup=localStorage.getItem('borgnet-image-source');}catch{}
if(!['frontier','community','local'].includes(sourceGroup))sourceGroup=imageSource({id:savedImageModel()});
function savedImageModel(){try{return localStorage.getItem('borgnet-image-model')||'';}catch{return '';}}
function rememberImageModel(){try{localStorage.setItem('borgnet-image-model',q('#localImageModel').value);localStorage.setItem('borgnet-image-model-'+sourceGroup,q('#localImageModel').value);}catch{}}
async function request(path,body){if(body!==undefined||!token)token=(await(await fetch('/api/state')).json()).token;const r=await fetch('/api/images/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-BorgNet-Token':token},body:JSON.stringify(body)});if(!r.ok){let e;try{e=await r.json();}catch{}throw Error(clean(e?.error||`Local service returned ${r.status}`));}return r;}
function panel(id,title,subtitle,content){const p=make('section',null,'panel local-mode-panel');p.id=id+'Panel';const h=make('div',null,'panel-heading');const text=make('div');text.append(make('p','IMAGE WORKSPACE','eyebrow'),make('h1',title),make('p',subtitle));h.append(text);p.append(h);p.insertAdjacentHTML('beforeend',content);q('#historyPanel').parentElement.append(p);const b=make('button',title);b.dataset.tab=id;b.addEventListener('click',()=>tab(id));q('.tabs').append(b);return p;}
panel('imagegen','Image generation','Your existing connections for images and chat.',`<form id="localImageForm" class="local-form"><div id="imageSourceSwitch" class="image-source-switch" role="group" aria-label="Image model source"><button type="button" data-source="frontier">Frontier</button><button type="button" data-source="community">Open &amp; community</button><button type="button" data-source="local">Local</button></div><p id="imageSourceHint" class="caption"></p><div class="local-controls"><label>Image model<select id="localImageModel"></select></label><label>Generation mode<select id="localImageMode"><option value="draft">Draft · fewer steps</option><option value="balanced" selected>Balanced · model default</option><option value="detail">Detail · more steps</option></select></label><label>Size<select id="localImageSize"></select></label></div><p id="localImageInfo" class="caption"></p><label>Image prompt<textarea id="localImagePrompt" rows="4" maxlength="4000" required placeholder="Describe the image you want to create"></textarea></label><details><summary>Generation settings</summary><label>Negative prompt<textarea id="localImageNegative" rows="2" maxlength="2000"></textarea></label><div class="local-controls"><label>Steps<input id="localImageSteps" type="number" required></label><label>Seed (-1 for random)<input id="localImageSeed" type="number" value="-1" min="-1" max="2147483647"></label></div></details><button id="localImageGenerate" class="primary" disabled>Generate image ↑</button><button id="localImageConnect" type="button" class="subtle">Connect image API</button><button id="localImageRefresh" type="button" class="subtle">Refresh models</button><p id="localImageState" class="caption local-state" role="status"></p></form><div id="localImageOutput"></div><h2>Recent images</h2><p id="localImageActionStatus" class="caption local-state" role="status"></p><div id="localImageGallery" class="local-gallery"></div><details><summary>Recently deleted</summary><p class="caption">Deleted images stay here until restored.</p><div id="localImageTrash" class="local-gallery"></div></details><button id="clearImageHistory" type="button" class="danger clear-image-history">Clear history</button>`);
function renderSourceModels(previous=''){
 const visible=imageModels.filter(m=>imageSource(m)===sourceGroup);
 if(!previous){try{previous=localStorage.getItem('borgnet-image-model-'+sourceGroup)||savedImageModel();}catch{}}
 q('#localImageModel').replaceChildren(...visible.map(m=>new Option(m.label+(m.installed?'':' · API key required'),m.id)));
 q('#localImageModel').value=(visible.find(m=>m.id===previous)||visible.find(m=>m.installed)||visible[0])?.id||'';
 q('#imageSourceSwitch').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.source===sourceGroup)));
 q('#imageSourceHint').textContent={frontier:'OpenAI, Gemini and Grok through API or supported sign-in.',community:'OpenRouter, AI Horde and Pollinations. OpenRouter also lists proprietary models; availability and pricing depend on the selected model.',local:'Runs on this computer. Bonsai unloads BitNet before rendering, then releases its own memory.'}[sourceGroup];
 if(visible.length)rememberImageModel();
 imageSettings();
 if(!visible.length)q('#localImageInfo').textContent='No models installed or configured in this group.';
}
q('#imageSourceSwitch').querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{
 if(running){q('#localImageState').textContent='Wait for the current generation to finish before switching model sources.';return;}
 if(feed){pauseFeed('Model source changed.');feed=null;}
 sourceGroup=button.dataset.source;
 try{localStorage.setItem('borgnet-image-source',sourceGroup);}catch{}
 renderSourceModels();
}));
const clearDialog=make('dialog');
clearDialog.innerHTML=`<h2>Clear image history?</h2><p class="caption">Permanently remove all images and prompt entries from Recent images and Recently deleted, including their saved library files. This cannot be undone. Copies in Downloads and provider-side records are unaffected.</p><p id="clearImageHistoryStatus" role="status"></p><div class="dialog-footer"><button id="cancelClearImageHistory" type="button">Cancel</button><button id="confirmClearImageHistory" type="button" class="danger">Clear history permanently</button></div>`;
document.body.append(clearDialog);
q('#clearImageHistory').onclick=()=>{if(running){q('#localImageActionStatus').textContent='Wait for generation to finish before clearing history.';return;}if(feed?.active)pauseFeed('Feed paused.');q('#clearImageHistoryStatus').textContent='';clearDialog.showModal();};
q('#cancelClearImageHistory').onclick=()=>clearDialog.close();
q('#confirmClearImageHistory').onclick=async()=>{const button=q('#confirmClearImageHistory');button.disabled=true;try{const result=await(await request('imagegen/clear-history',{confirm:true})).json();feed=null;feedButtons();q('#imageFeedItems').replaceChildren();q('#localImageOutput').replaceChildren();delete q('#localImageOutput').dataset.imageId;await gallery();q('#localImageActionStatus').textContent=result.message;clearDialog.close();}catch(error){q('#clearImageHistoryStatus').textContent=error.message;}finally{button.disabled=false;}};
const imageDialog=make('dialog');imageDialog.innerHTML=`<form id="imageApiForm"><div class="dialog-heading"><h2>Connect image API</h2><button id="imageApiClose" type="button" class="icon">×</button></div><label>Provider<select name="provider"><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option><option value="xai">xAI / Grok</option><option value="openrouter">OpenRouter · image models</option><option value="pollinations">Pollinations · Pollen credits</option><option value="horde">AI Horde · free community queue</option></select></label><label>API key<input name="api_key" type="password" required autocomplete="new-password"></label><p class="caption">Stored locally, separately from your configuration. AI Horde works anonymously without a key; add an optional account key for queue priority. Workers can see your prompts and images. Anonymous results are shared for dataset use; use an account key to request unshared results. Pollinations uses your Pollen allowance/credits. Your saved OpenRouter connection key is reused automatically for image generation. Image models may charge credits independently of free text models. Existing configured provider credentials are reused when available.</p><p id="imageApiStatus" role="status"></p><button class="primary">Save and discover models</button></form>`;document.body.append(imageDialog);
q('#localImageConnect').addEventListener('click',()=>{q('#imageApiForm').reset();imageDialog.showModal();});q('#imageApiClose').addEventListener('click',()=>imageDialog.close());
q('#imageApiForm').addEventListener('submit',async e=>{e.preventDefault();try{if(!token)token=(await(await fetch('/api/state')).json()).token;const r=await fetch('/api/image-providers',{method:'POST',headers:{'Content-Type':'application/json','X-BorgNet-Token':token},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(!r.ok)throw Error('Could not save image API key');e.target.reset();imageDialog.close();window.dispatchEvent(new Event('borgnet-image-credentials-changed'));await refreshImages();}catch(e){q('#imageApiStatus').textContent=e.message;}});
function selectedImage(){return imageModels.find(x=>x.id===q('#localImageModel').value);}
function imageSettings(){feedButtons();const m=selectedImage();if(!m){q('#localImageGenerate').disabled=true;q('#localImageInfo').textContent='No image model available.';return;}q('#localImageMode').replaceChildren(...(m.modes||[['draft','Draft · fewer steps'],['balanced','Balanced · model default'],['detail','Detail · more steps']]).map(x=>new Option(x[1],x[0])));q('#localImageMode').value=m.modes?'auto':'balanced';q('#localImageSteps').disabled=Boolean(m.modes);q('#localImageSeed').disabled=Boolean(m.modes);q('#localImageSize').replaceChildren(...m.sizes.map(x=>new Option(x,x)));q('#localImageSize').value=m.default_size;q('#localImageSteps').min=m.min_steps;q('#localImageSteps').max=m.max_steps;steps();q('#localImageInfo').textContent=`${m.label} · ${m.backend==='signedin'?'Existing sign-in':m.backend==='api'?'Cloud image API':m.backend==='local_cli'?'Local Metal runtime':'Remote image runtime'} · ${clean(m.status)} · Text to image`;q('#localImageGenerate').disabled=running||!m.installed;}
function steps(){const m=selectedImage();if(m)q('#localImageSteps').value=q('#localImageMode').value==='draft'?m.min_steps:q('#localImageMode').value==='detail'?m.max_steps:m.default_steps;}
async function refreshImages(){if(running||refreshing){refreshPending=true;return;}refreshing=true;refreshPending=false;q('#localImageState').textContent='Discovering installed image models…';try{const d=await(await request('imagegen/models')).json(),previous=q('#localImageModel').value||savedImageModel();imageModels=d.models||[];renderSourceModels(previous);q('#localImageState').textContent=`${imageModels.filter(m=>!['api','signedin'].includes(m.backend)&&m.installed).length} local model(s) · ${imageModels.filter(m=>m.backend==='api'&&m.installed).length} API model(s) with credentials · ${imageModels.filter(m=>m.backend==='signedin').length} signed-in image connection(s). Cloud generation uses your provider account.`;await gallery();}catch(e){q('#localImageState').textContent=e.message;q('#localImageGenerate').disabled=true;}finally{refreshing=false;if(refreshPending&&!running)refreshImages();}}
function imageURL(x){return /^\/api\/imagegen\/images\/\d{8}-\d{6}-[a-f0-9]{8}$/.test(x)?window.borgnetMediaURL(x.replace('/api/','/api/images/')):'';}
function imageActions(x,trashed=false){const row=make('div',null,'local-image-actions');for(const [action,label] of (trashed?[['restore','Restore']]:[...(imageURL(x.url)?[['save','Save to Downloads']]:[]),['delete','Delete']])){const b=make('button',label,'subtle');b.type='button';b.addEventListener('click',async()=>{b.disabled=true;const status=q('#localImageActionStatus');try{const d=await(await request('imagegen/library',{id:x.id,action})).json();status.textContent=d.message;if(action==='delete'&&q('#localImageOutput').dataset.imageId===x.id)q('#localImageOutput').replaceChildren();if(action==='delete')q('#imageFeedItems').querySelectorAll('[data-image-id]').forEach(card=>{if(card.dataset.imageId===x.id)card.remove();});await gallery();}catch(e){status.textContent=e.message;}finally{b.disabled=false;}});row.append(b);}return row;}
function showImage(x){const out=q('#localImageOutput'),url=imageURL(x.url);out.replaceChildren();out.dataset.imageId=x.id;out.append(make('p',x.prompt,'local-message'));if(url){const img=make('img',null,'local-image');img.src=url;img.alt=x.prompt||'Generated image';out.append(img);}if(x.error)out.append(make('p',x.error,'caption'));out.append(window.borgnetProviderResponses(x),imageActions(x));}
async function gallery(){const d=await(await request('imagegen/history')).json();for(const [key,selector,trashed] of [['images','#localImageGallery',false],['trash','#localImageTrash',true]]){const list=q(selector);list.replaceChildren();for(const x of (d[key]||[])){const url=imageURL(x.url);const card=make('div',null,'local-image-card'),b=make('button');b.type='button';if(url){const img=make('img');img.src=url;img.alt=x.prompt||'Generated image';b.append(img);}else b.textContent='Generation did not produce an image · View response';b.addEventListener('click',()=>showImage(x));card.append(b,window.borgnetProviderResponses(x),imageActions(x,trashed));list.append(card);}if(trashed&&!list.children.length)list.append(make('p','No deleted images.','caption'));}}
// Feed requests share the single-image busy flag and existing authenticated adapter.
const feedControls=make('section',null,'image-feed-controls');
feedControls.hidden=true;
feedControls.innerHTML=`<div class="local-controls"><label>Feed limit<select id="imageFeedLimit"><option value="4">4 images</option><option value="8" selected>8 images</option><option value="16">16 images</option><option value="30">30 images</option></select></label><button id="imageFeedStart" type="button">Start scrolling feed</button><button id="imageFeedPause" type="button" disabled>Pause feed</button><button id="imageFeedResume" type="button" disabled>Resume feed</button></div><p class="caption">Uses the selected model and prompt. Scroll down for another variation, one request at a time. Each request uses your provider allowance or API credits. Pause stops future requests; a request already sent may finish.</p><p id="imageFeedStatus" class="caption" role="status">Feed is off.</p><div id="imageFeedViewport" class="image-feed-viewport" tabindex="0" aria-label="Generated image feed"><div id="imageFeedItems" class="image-feed-items"></div><div id="imageFeedEnd" class="image-feed-end">Scroll down for more variations.</div></div><button id="imageFeedMore" type="button" disabled>Generate next variation</button>`;
q('#localImageOutput').before(feedControls);
let feed=null, feedPending=false;
const feedStatus=text=>{q('#imageFeedStatus').textContent=text;};
function grokFeedAvailable(){const m=selectedImage();return Boolean(m&&(m.id==='signedin::grok'||m.id.startsWith('api::xai::')));}
function feedButtons(){const available=grokFeedAvailable();feedControls.hidden=!available;if(!available&&feed)feed.active=false;q('#imageFeedMore').disabled=!feed?.active||running;q('#imageFeedStart').disabled=running||!available;q('#imageFeedPause').disabled=!feed?.active;q('#imageFeedResume').disabled=!feed||feed.active||feed.count>=feed.limit||running;}
function pauseFeed(reason='Feed paused.'){if(feed)feed.active=false;feedStatus(reason);feedButtons();}
function settingsSnapshot(){return {model_id:selectedImage().id,prompt:q('#localImagePrompt').value.trim(),negative_prompt:q('#localImageNegative').value,size:q('#localImageSize').value,steps:Number(q('#localImageSteps').value),seed:Number(q('#localImageSeed').value),quality:q('#localImageMode').value};}
function appendFeedImage(x){const url=imageURL(x.url);if(!url)return;const card=make('article',null,'local-image-card');card.dataset.imageId=x.id;const open=make('button'),img=make('img');open.type='button';open.className='image-feed-open';open.setAttribute('aria-label','Open generated variation');img.src=url;img.alt=x.prompt||'Generated variation';img.className='local-image';open.append(img);open.addEventListener('click',()=>{showImage(x);q('#localImageOutput').scrollIntoView({block:'nearest',behavior:'smooth'});});card.append(open,imageActions(x));q('#imageFeedItems').append(card);}
async function feedNext(){
 if(!grokFeedAvailable()||!feed?.active||running||feedPending||document.hidden||!q('#imagegenPanel').classList.contains('active'))return;
 if(feed.count>=feed.limit){pauseFeed(`Feed complete · ${feed.count}/${feed.limit} requests. Start a new feed for more.`);return;}
 if(!selectedImage()?.installed||selectedImage().id!==feed.settings.model_id){pauseFeed('Selected connection changed. Start a new feed.');return;}
 const session=feed;running=true;feedPending=true;session.count++;q('#localImageGenerate').disabled=true;feedButtons();feedStatus(`Generating variation ${session.count} of ${session.limit}…`);
 try{const x=await(await request('imagegen/generate',session.settings)).json();appendFeedImage(x);await gallery();if(session.count>=session.limit)pauseFeed(`Feed complete · ${session.count}/${session.limit} requests.`);else feedStatus(session.active?`${session.count}/${session.limit} requests · scroll down for another variation.`:'Feed paused. The last requested image has arrived.');}
 catch(error){pauseFeed(`Feed paused · ${error.message} No automatic retry.`);await gallery().catch(()=>{});}
 finally{running=false;feedPending=false;imageSettings();feedButtons();if(refreshPending)refreshImages();}
}
q('#imageFeedStart').onclick=()=>{if(!grokFeedAvailable())return;if(running||!selectedImage()?.installed)return feedStatus('Select an available image model first.');if(!q('#localImageForm').reportValidity())return;const settings=settingsSnapshot();if(!settings.prompt)return;feed={settings,limit:Number(q('#imageFeedLimit').value),count:0,active:true};q('#imageFeedItems').replaceChildren();q('#imageFeedViewport').scrollTop=0;previousScroll=0;feedNext();};
q('#imageFeedMore').onclick=()=>feedNext();
q('#imageFeedPause').onclick=()=>pauseFeed();
q('#imageFeedResume').onclick=()=>{if(!grokFeedAvailable()||!feed||running||feed.count>=feed.limit)return;feed.active=true;feedButtons();feedNext();};
// A real downward scroll is required for each additional request. Layout changes
// and newly loaded images alone never consume another generation credit.
let previousScroll=0;
q('#imageFeedViewport').addEventListener('scroll',()=>{const panel=q('#imageFeedViewport');const downward=panel.scrollTop>previousScroll;previousScroll=panel.scrollTop;if(!downward||!feed?.active)return;const end=q('#imageFeedEnd').getBoundingClientRect(),view=panel.getBoundingClientRect();if(end.top<view.bottom+240&&end.bottom>view.top)feedNext();},{passive:true});
for(const id of ['localImageModel','localImageMode','localImageSize','localImagePrompt','localImageNegative','localImageSteps','localImageSeed','imageFeedLimit'])q('#'+id).addEventListener('input',()=>{if(feed){pauseFeed('Settings changed. Start a new feed to use them.');feed=null;feedButtons();}});
window.addEventListener('borgnet-tab-change',event=>{if(event.detail!=='imagegen'&&feed?.active)pauseFeed('Feed paused while you are away.');});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&feed?.active)pauseFeed('Feed paused while this window is hidden.');});
window.addEventListener('borgnet-connections-changed',()=>{if(feed?.active)pauseFeed('Connections changed. Review the selected model before resuming.');});
q('#localImageModel').addEventListener('change',()=>{rememberImageModel();imageSettings();});q('#localImageMode').addEventListener('change',steps);q('#localImageRefresh').addEventListener('click',refreshImages);
q('#localImageForm').addEventListener('submit',async e=>{e.preventDefault();if(running||!selectedImage()?.installed)return;if(feed?.active)pauseFeed('Feed paused for single-image generation.');running=true;feedButtons();q('#localImageGenerate').disabled=true;q('#localImageState').dataset.error='false';q('#localImageOutput').replaceChildren();q('#localImageState').textContent=selectedImage().id.startsWith('api::horde::')?'Waiting for AI Horde · queue allowance up to 20 minutes. Temporary connection failures are retried without creating another job.':'Loading image runtime and generating…';try{const x=await(await request('imagegen/generate',{model_id:selectedImage().id,prompt:q('#localImagePrompt').value,negative_prompt:q('#localImageNegative').value,size:q('#localImageSize').value,steps:Number(q('#localImageSteps').value),seed:Number(q('#localImageSeed').value),quality:q('#localImageMode').value})).json();showImage(x);q('#localImageState').textContent='Image saved. '+clean(x.restoration_error?('Text runtime restoration needs attention: '+x.restoration_error):'');await gallery();}catch(e){q('#localImageState').dataset.error='true';q('#localImageState').textContent=e.message;await gallery().catch(()=>{});}finally{running=false;imageSettings();feedButtons();if(refreshPending)refreshImages();}});
window.addEventListener('borgnet-tab-change',event=>{if(event.detail==='imagegen')refreshImages();});
window.addEventListener('borgnet-connections-changed',()=>refreshImages());
for(const id of ['localImagePrompt'])q('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.target.form.requestSubmit();}});
})();
